BookStore/Models/Book.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models
{
    public class Book
    {
        public string Title { get; }

        public string Author { get; }

        public string Style { get; }

        public string Theme { get; }

        public string PublishingHouse { get; }

        public int PagesCount { get; }

        public int Cost { get; }

        public DateTime PublishedAt { get; }

        public Book(
            string title,
            string author,
            string style,
            string theme,
            string publishingHouse,
            int pagesCount,
            int cost,
            DateTime publishedAt
        )
        {
            Title = title;
            Author = author;
            Style = style;
            Theme = theme;
            PublishingHouse = publishingHouse;
            PagesCount = pagesCount;
            Cost = cost;
            PublishedAt = publishedAt;
        }

        public bool IsValid()
        {
            return Title != null
                && Author != null
                && Style != null
                && Theme != null
                && PublishingHouse != null
                && PagesCount != 0;
        }
    }
}

BookStore/Models/BookFilterViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models
{
    public class BookFilterViewModel
    {
        public string Title { get; set; }
        public string Author { get; set; }
        public string Style { get; set; }
        public string Theme { get; set; }
        public string PublishingHouse { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value greater than or equal to {1}")]
        public int? MinPages { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value greater than or equal to {1}")]
        public int? MaxPages { get; set; }

        [Range(
            1,
            double.MaxValue,
            ErrorMessage = "Please enter a value greater than or equal to {1}"
        )]
        public int? MinCost { get; set; }

        [Range(
            1,
            double.MaxValue,
            ErrorMessage = "Please enter a value greater than or equal to {1}"
        )]
        public int? MaxCost { get; set; }

        public DateTime? PublishedAt { get; set; }
    }
}

BookStore/Models/LoginModel.cs
namespace BookStore.Models
{
    public class LoginModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

BookStore/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BookStore/Controllers/AdminController.cs
using System.Data.SqlTypes;
using BookStore.Models;
using BookStore.Services;
using BookStore.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddBook([FromBody] Book book)
        {
            if (!book.IsValid())
            {
                return BadRequest(book);
            }

            BookService.WriteBookToFile(book);
            BooksStore.LoadStore("storage.txt");
            return Ok();
        }

        [HttpPost]
        public IActionResult Login([FromBody] LoginModel model)
        {
            var username = model.UserName;
            var password = model.Password;

            if (username == "admin" || password == "admin")
            {
                var json = new { isUserExist = "true" };
                return Json(json);
            }
            else
            {
                return Json(new { isUserExist = "false" });
            }
        }
    }
}

BookStore/Controllers/BookController.cs
using System;
using System.Text;
using BookStore.Models;
using BookStore.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class BookController : Controller
    {
        [HttpPost]
        public IActionResult CreateFile(
            string title,
            string author,
            string style,
            string theme,
            string publishingHouse,
            int pagesCount,
            decimal cost,
            string publishedAt
        )
        {
            var content = new StringBuilder();
            content.AppendLine($"Title: {title}");
            content.AppendLine($"Author: {author}");
            content.AppendLine($"Style: {style}");
            content.AppendLine($"Theme: {theme}");
            content.AppendLine($"Publishing House: {publishingHouse}");
            content.AppendLine($"Pages Count: {pagesCount}");
            content.AppendLine($"Cost: {cost}");
            content.AppendLine($"Published At: {publishedAt}");

            var fileBytes = Encoding.UTF8.GetBytes(content.ToString());
            var fileName = $"{title}_{author}.txt";

            return File(fileBytes, "text/plain", fileName);
        }

        [HttpGet]
        public IActionResult FilterBooks(BookFilterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("~/Views/Home/Index.cshtml", model);
            }

            var filteredBooks = BookService.FilterData(
                model.Title,
                model.Author,
                model.Style,
                model.Theme,
                model.PublishingHouse,
                model.MinPages,
                model.MaxPages,
                model.MinCost,
                model.MaxCost,
                model.PublishedAt
            );
            return View("FilteredBooks", filteredBooks);
        }

        [HttpGet]
        public IActionResult GetFilteredBooksJson(BookFilterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                // Handle validation errors (e.g., return a JSON response with validation error details)
                return BadRequest(ModelState);
            }

            var filteredBooks = BookService.FilterData(
                model.Title,
                model.Author,
                model.Style,
                model.Theme,
                model.PublishingHouse,
                model.MinPages,
                model.MaxPages,
                model.MinCost,
                model.MaxCost,
                model.PublishedAt
            );
            return Json(filteredBooks);
        }
    }
}

BookStore/Controllers/HomeController.cs
using System;
using System.Linq;
using BookStore.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [HttpGet]
        public IActionResult FilterBooks(
            string title,
            string author,
            string style,
            string theme,
            string publishingHouse,
            int? minPages,
            int? maxPages,
            int? minCost,
            int? maxCost,
            DateTime? publishedAt
        )
        {
            var filteredBooks = BookService.FilterData(
                title,
                author,
                style,
                theme,
                publishingHouse,
                minPages,
                maxPages,
                minCost,
                maxCost,
                publishedAt
            );
            return View("FilteredBooks", filteredBooks);
        }

        [HttpGet]
        public IActionResult GetFilteredBooksJson(
            string title,
            string author,
            string style,
            string theme,
            string publishingHouse,
            int? minPages,
            int? maxPages,
            int? minCost,
            int? maxCost,
            DateTime? publishedAt
        )
        {
            var filteredBooks = BookService.FilterData(
                title,
                author,
                style,
                theme,
                publishingHouse,
                minPages,
                maxPages,
                minCost,
                maxCost,
                publishedAt
            );
            return Json(filteredBooks);
        }
    }
}

BookStore/Controllers/PhraseController.cs
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class PhraseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BookStore/Views/About/Index.cshtml
@model IEnumerable<BookStore.Models.Book>

@{
    ViewData["Title"] = "Book Filter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<h1>That site that's book shop </h1>

BookStore/Views/Admin/Index.cshtml
@model BookStore.Models.LoginModel

@{
    ViewData["Title"] = "Admin page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="~/css/admin.css">
<h1>Admin page</h1>


    <p>Welcome, admin!</p>

<form id="loginForm">
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name="UserName">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="Password">
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

<div id="loginMessage"></div>

<div id="additional_content">
    <form id="addBookForm">
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="Title">
        </div>
        <div class="mb-3">
            <label for="author" class="form-label">Author</label>
            <input type="text" class="form-control" id="author" name="Author">
        </div>
        <div class="mb-3">
            <label for="style" class="form-label">Style</label>
            <input type="text" class="form-control" id="style" name="Style">
        </div>
        <div class="mb-3">
            <label for="theme" class="form-label">Theme</label>
            <input type="text" class="form-control" id="theme" name="Theme">
        </div>
        <div class="mb-3">
            <label for="publishingHouse" class="form-label">Publishing House</label>
            <input type="text" class="form-control" id="publishingHouse" name="PublishingHouse">
        </div>
        <div class="mb-3">
            <label for="pagesCount" class="form-label">Pages Count</label>
            <input type="number" class="form-control" id="pagesCount" name="PagesCount">
        </div>
        <div class="mb-3">
            <label for="cost" class="form-label">Cost</label>
            <input type="number" class="form-control" id="cost" name="Cost">
        </div>
        <div class="mb-3">
            <label for="publishedAt" class="form-label">Published At</label>
            <input type="date" class="form-control" id="publishedAt" name="PublishedAt">
        </div>
        <button type="submit" class="btn btn-primary">Add Book</button>
    </form>

</div>

<script src="~/js/admin.js"></script>

BookStore/Views/Book/FilteredBooks.cshtml
@{
    ViewData["Title"] = "Filtered Books";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<h1>@ViewData["Title"]</h1>

<p id="message"></p>
<button onclick="goBack()">Go Back</button>
<button onclick="toggleView()">Toggle View</button>
<table id="booksTable" class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Style</th>
            <th>Theme</th>
            <th>Publishing House</th>
            <th>Pages Count</th>
            <th>Cost</th>
            <th>Published At</th>
            <th>Download</th>
        </tr>
    </thead>
    <tbody>
        <!-- Здесь будут отображены книги -->
    </tbody>
</table>
<pre id="jsonView" style="display:none;"></pre>
<pre id="plainTextView" style="display:none;"></pre>



<script src="~/js/filteredbooks.js"></script>

BookStore/Views/Home/About.cshtml
@model IEnumerable<BookStore.Models.Book>

@{
    ViewData["Title"] = "Book Filter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<h1>That site that's book shop </h1>

BookStore/Views/Home/Index.cshtml
@model BookStore.Models.BookFilterViewModel

@{
    ViewData["Title"] = "Book Filter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<h1>@ViewData["Title"]</h1>

<form id="filterForm" method="get" action="@Url.Action("FilterBooks", "Book")">
    <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="form-control" id="title" name="Title" />
        <span class="text-danger" id="titleError"></span>
    </div>
    <div class="form-group">
        <label for="author">Author:</label>
        <input type="text" class="form-control" id="author" name="Author" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="style">Style:</label>
        <input type="text" class="form-control" id="style" name="Style"  />
        <span asp-validation-for="Style" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="theme">Theme:</label>
        <input type="text" class="form-control" id="theme" name="Theme"  />
        <span asp-validation-for="Theme" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="publishingHouse">Publishing House:</label>
        <input type="text" class="form-control" id="publishingHouse" name="PublishingHouse" />
        <span asp-validation-for="PublishingHouse" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="minPages">Minimum Pages:</label>
        <input type="number" class="form-control" id="minPages" name="MinPages" data-validation="required" />
        <span class="text-danger" id="minPagesError"></span>
        <span asp-validation-for="MinPages" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="maxPages">Maximum Pages:</label>
        <input type="number" class="form-control" id="maxPages" name="MaxPages" data-validation="required" />
        <span class="text-danger" id="maxPagesError"></span>
        <span asp-validation-for="MaxPages" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="minCost">Minimum Cost:</label>
        <input type="number" class="form-control" id="minCost" name="MinCost"  />
        <span asp-validation-for="MinCost" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="maxCost">Maximum Cost:</label>
        <input type="number" class="form-control" id="maxCost" name="MaxCost"  />
        <span asp-validation-for="MaxCost" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="publishedAt">Published At:</label>
        <input type="date" class="form-control" id="publishedAt" name="PublishedAt"  />
        <span asp-validation-for="PublishedAt" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
</form>


<script>
    function validateForm() {
        var form = document.getElementById("filterForm");
        var elements = form.elements;
        var isValid = true;

        for (var i = 0; i < elements.length; i++) {
            var element = elements[i];
            var validation = element.dataset.validation;

            if (validation === "required") {
                if (element.value.trim() === "") {
                    isValid = false;
                    showError(element);
                } else {
                    hideError(element);
                }
            }
            // Add additional validation rules as needed
        }

        return isValid;
    }

    function showError(element) {
        var errorId = element.id + "Error";
        var errorElement = document.getElementById(errorId);
        if (errorElement) {
            errorElement.innerText = element.dataset.validationMessage || "Field is required";
        }
    }

    function hideError(element) {
        var errorId = element.id + "Error";
        var errorElement = document.getElementById(errorId);
        if (errorElement) {
            errorElement.innerText = "";
        }
    }

    document.getElementById("filterForm").onsubmit = validateForm;
</script>

BookStore/Views/Phrase/Index.cshtml
@{
    ViewData["Title"] = "Phrase Generator";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<h1>Phrase Generator</h1>

<div id="quote_container">

</div>

<div id="quote_author_container">

</div>

<button onclick="displayQuote()">Generate Again</button>

<script src="~/js/phrase.js"></script>

BookStore/Views/Shared/_Header.cshtml
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ775pPahUibscwPAXsr" crossorigin="anonymous">

<header class="bg-primary text-white text-center py-3">
    <h1>My Book Store</h1>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "About")">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Phrase")">Phrase Generator</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Admin")">Admin page</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Book Store</title>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ775pPahUibscwPAXsr" crossorigin="anonymous">
</head>
<body>
    @Html.Partial("_Header")
    <div class="container mt-4">
        @RenderBody()
    </div>
    <footer class="bg-light text-center py-3 mt-4">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-f2S5f5zzQ5daOgDO/rFqtNJ0g6bOdyC8LlF9qOehupDEEzRQlueufG/+ha9n+TbZ" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-3q2tBLydpM1bW5TUn3blFzP6R4/pLT5h3lM9k5E4JfzvN4Ij6mEQVLe7gg4fow9D" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rQmYIYOqB4bAJ3EVOQzA4vS+gp4ylJ1KhFlDBBaT5j8E8vK0a" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>